<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDnIFWyD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDnIFWyD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDnIFWyD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDnIFWyD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDnIFWyD\App_KernelDevDebugContainer([
    'container.build_hash' => 'DnIFWyD',
    'container.build_id' => 'e0dbe5f5',
    'container.build_time' => 1681865361,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDnIFWyD');
