<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMxqlxoy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMxqlxoy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMxqlxoy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMxqlxoy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMxqlxoy\App_KernelDevDebugContainer([
    'container.build_hash' => 'Mxqlxoy',
    'container.build_id' => 'c633ced1',
    'container.build_time' => 1681832693,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMxqlxoy');
